name: Build VSF

on:
  push:
    branches: [ 16.0 ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - run: |
        echo "-------- Deploying https://vsfdemo16.labs.odoogap.com/ "
        /home/egap/.scripts/update
